### ISSUE TITLE
Polling error with conductor-python 1.0.33

### ISSUE THREAD

**Issue by phmurias-invitae** [conductor-sdk/conductor-python#107]
When migrating from version 1.0.32 to version 1.0.33 task polling stopped working.

The worker is polling to an empty task queue, and we get:

```
File ".../site-packages/conductor/client/http/api_client.py", line 612, in __deserialize_model
    klass.attribute_map[attr] in data and
TypeError: a bytes-like object is required, not 'str'
```

It seems that the error originated in this [commit](https://github.com/conductor-sdk/conductor-python/commit/3bbaa5ea5d43ff8835b7fc7b6dfb9ca4d8d3fb8a#diff-f4f73658d4f32e4ecc23556d4e26e2a7f362a1636e9ca4127a78f241939bedb4L237) when the following check was removed:

```
        if data == b'':
            return None
```

**Comment by gardusig** [comment]
Yes, you're right! This bug should be solved by next release ✅
Thanks for the feedback!
