### ISSUE TITLE
Cannot access conductor-server with URL based creds

### ISSUE THREAD

**Issue by marcocrasso** [conductor-sdk/conductor-python#119]
Prior Python client for Conductor server works with requests, which parses creds from URLs if any, and makes an authentification header. This is useful for intranet servers.

### How to reproduce

```
configuration = Configuration()
        self.assertEqual(
            configuration.host,
            'http://user:pass@your_secured_server:8080/api/'
        )
```

Trying to reach any resource of the above configured server will get a 401 error.

**Comment by gardusig** [comment]
Done: #120
