### ISSUE TITLE
How to start more than one processes for a single task?

### ISSUE THREAD

**Issue by BrandonDotLin** [conductor-sdk/conductor-python#131]
Is it possible to start multiple process for a single task? Start multiple client would be not so convenient

**Comment by gardusig** [comment]
Hey @BrandonDotLin, we're working on some improvements for that, it will probably fix your goal by #130 merge.

In the meantime, there is a [documentation](https://github.com/conductor-sdk/conductor-python/blob/main/docs/worker/README.md#run-workers) on how to achieve multiple workers.

Long short story - just append as many workers as needed. Each one will work as a independent process, regardless of the task name.

**Comment by BrandonDotLin** [comment]
This solved my problem. Thanks for your useful information.
