### ISSUE TITLE
 [Bug] Worker with generic input and output is not supported

### ISSUE THREAD

**Issue by george-kirkman** [conductor-sdk/conductor-python#234]
Hi there!

There was work done last year to enhance the Worker to be able to execute functions with generic input/output, instead of Task/TaskResult: https://github.com/conductor-sdk/conductor-python/pull/116

This PR missed a line. It creates an `execute_function_input` which is either `task` or `task.input_data`, based on whether the function expects a Task or not, but it consumes `task` instead of `execute_function_input` on [L66](https://github.com/conductor-sdk/conductor-python/blob/2cc39d3ef45ed710abbb1934852f18229738d818/src/conductor/client/worker/worker.py#L66C1-L66C62), thereby forgetting what it knew about the function's input parameter type. 

L66 should read: 
`task_result.output_data = self.execute_function(execute_function_input)` instead of
`task_result.output_data = self.execute_function(task)`.

**Comment by v1r3n** [comment]
Hi @george-kirkman this is addressed in the latest version now.
