### ISSUE TITLE
Conductor API for updateWorkflowDef doesn't support updating onStateChange values

### ISSUE THREAD

**Issue by matteius** [conductor-sdk/conductor-python#237]
Conductor API for updateWorkflowDef doesn't support updating onStateChange values.

```
        task.on_state_change = {
            "onScheduled,onStart,onSuccess,onFailed,onCancelled": [
                {
                    "type": "task_status_changed",
                    "payload": {"task": "${%s}" % task.task_reference_name, "workflow": "${workflow}"},
                }
            ]
        }
```

but updated workflow is missing this data because client doesn't have getter/setter for this newer attribute.

**Comment by v1r3n** [comment]
Hi @matteius this has been addressed in the latest version.  See https://github.com/conductor-sdk/conductor-python/blob/main/examples/task_status_change_audit.py for example.
