### ISSUE TITLE
Refactor API client to use `requests` package instead of `urllib3`

### ISSUE THREAD

**Issue by gardusig** [conductor-sdk/conductor-python#83]
New package: https://pypi.org/project/requests/

HTTP client was implemented with `swagger code generator` tool, which was a quick handy solution, but may be upgraded for more detailed usage.

Updates should probably lie within `api_client.py` and `rest.py` at http folder: `src/conductor/client/http`

**Comment by marcocrasso** [comment]
Collaterally, by switching to **requests** you will restore a behaviour that was in previous community conductor Python client, which is supporting user:pass in URIs as [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt), which at the moment of writing this comment is not available in this Conductor Python. I believe restoring such behaviour would be nice for backward compatibility, with or without **requests**.

**Comment by gardusig** [comment]
Done: https://github.com/conductor-sdk/conductor-python/pull/143
