### ISSUE TITLE
Invalid value for `name`

### ISSUE THREAD

**Issue by BrandonDotLin** [conductor-sdk/conductor-python#94]
Failed to poll task for: xxx, 
conductor/client/http/models/task_def.py", line 265, in name
    raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `name`, must not be `None`

**Comment by BrandonDotLin** [comment]
@gardusig Thanks for your quick reply. Here is my task details:

{
         "taskType": "yyy",
         "status": "CANCELED",
         "inputData": {
            "zone_id": "Asia/Shanghai",
            "trade_date": "2222-01-01"
         },
         "referenceTaskName": "zzz",
         "retryCount": 0,
         "seq": 1,
         "correlationId": "1000",
         "pollCount": 1,
         "taskDefName": "yyy",
         "scheduledTime": 1656034220053,
         "startTime": 1656034220304,
         "endTime": 1656034363790,
         "updateTime": 1656034220304,
         "startDelayInSeconds": 0,
         "retried": true,
         "executed": true,
         "callbackFromWorker": true,
         "responseTimeoutSeconds": 3600,
         "workflowInstanceId": "cf077125-500c-4bde-b1fe-a7da674bcf96",
         "workflowType": "xxxxx",
         "taskId": "b4e66342-10a8-4e04-906e-99181813d6b5",
         "callbackAfterSeconds": 0,
         "outputData": {},
         "workflowTask": {
            "name": "yyy",
            "taskReferenceName": "zzz",
            "inputParameters": {
               
            },
            "type": "SIMPLE",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "ownerApp": "MFM",
               "createTime": 1656031810927,
               "createdBy": "",
               "name": "Update_Factor_Exposure",
               "description": "",
               "retryCount": 0,
               "timeoutSeconds": 3600,
               "inputKeys": [
                  "trade_date",
                  "zone_id"
               ],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 5,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {
                  
               },
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "test@qq.com",
               "pollTimeoutSeconds": 3600
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 1,
         "workflowPriority": 0,
         "iteration": 0,
         "taskDefinition": {
            "present": true
         },
         "loopOverTask": false,
         "taskStatus": "CANCELED",
         "queueWaitTime": 251,
         "logs": []
      }

**Comment by gardusig** [comment]
Hey @BrandonDotLin, can you also share the worker that you're using at `TaskHandler`?
Don't worry about its actual internals, the method signatures is enough.

**Comment by BrandonDotLin** [comment]
> Hey @BrandonDotLin, can you also share the worker that you're using at `TaskHandler`? Don't worry about its actual internals, the method signatures is enough.

workers = [
        UpdateExposureWorker("yyy"),
    
    ]

    # Start the worker processes and wait for their completion
    with TaskHandler(workers, configuration) as task_handler:
        task_handler.start_processes()
        task_handler.join_processes()

**Comment by gardusig** [comment]
Hey @BrandonDotLin, sorry for the late reply. I was able to reproduce your issue, and definitely it was a bug. Already fixed it, wrapping up a PR with that.

I'll attach the new release here once published! Thanks for the feedback :)

**Comment by gardusig** [comment]
Explanation: due to some recent changes at the client, it raised an exception if no task was polled (something that happens when the queue is empty).
